### ISSUE TITLE
Unable to make it work in fresh installation of laravel 10 and livewire 3

### ISSUE THREAD

**Issue by mozhuilungdsuo** [aliqasemzadeh/livewire-bootstrap-modal#10]
- I'm unable to make it work for livewire3. I'm pulling the master branch directly by adding the following code in my composer.json
` "repositories": [
        {
          "type": "package",
          "package": {
            "name": "aliqasemzadeh/livewire-bootstrap-modal",
            "version": "2.0.1",
            "source": {
              "type" : "git",
              "url" : "git://github.com/aliqasemzadeh/livewire-bootstrap-modal.git",
              "reference" : "master"
            },
            "dist": {
              "url": "https://github.com/aliqasemzadeh/livewire-bootstrap-modal/archive/master.zip",
              "type": "zip"
            }
          }
        }
      ]
`
- Getting the following response when i run
   `php artisan vendor:publish --tag=livewire-bootstrap-modal:views`
    `No publishable resources for tag [livewire-bootstrap-modal:views].`

- And getting the exception `Unable to find component: [modals]` when i add `<livewire:modals/>` to my layout.
 Please help. have to breaking my head over this. Thanks

**Comment by aliqasemzadeh** [comment]
Hi
I am working on this issue hope to fix it soon.

**Comment by B0TU** [comment]
Hi,

Is this already fixed?

**Comment by mozhuilungdsuo** [comment]
Hi @B0TU  I made a fork of this to make it work in livewire 3 https://github.com/mozhuilungdsuo/livewire-bootstrap-modal
