### ISSUE TITLE
Only arrays and Traversables can be unpacked

### ISSUE THREAD

**Issue by danyderigon** [aliqasemzadeh/livewire-bootstrap-modal#12]
I recently upgraded a Livewire 2 project to Livewire 3.
I also switched from the bastinald/laravel-livewire-modals package to yours.

Since then I've had this error: `Only arrays and Traversables can be unpacked`

I did, however, make a very simple modal

app/Http/Livewire/TestModal.php
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class TestModal extends Component
{
    public function render()
    {
        return view('livewire.test-modal');
    }
}

```

resources/views/livewire/test-modal.blade.php
```
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
            ></button>
        </div>
        <div class="modal-body">
            <p>Modal body text goes here.</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                Close
            </button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
    </div>
</div>

```

And I call it like that in another Livewire component : 
```
<button type="button" wire:click="$dispatch('showModal', 'test-modal')">
    {{ __('Display test modal') }}
</button>
```

Do you have any idea what the problem is? 

The complete error : 

https://flareapp.io/share/x7Xw4nwP/claim/FNle9JTUDEyBnKGaBz8BILLUrfJlMNK0

**Comment by aliqasemzadeh** [comment]
Hi Please give me more detail about your project.

**Comment by danyderigon** [comment]
Sorry I closed this issue because my stack was completely broken ...

Nevertheless, I have a question: 

The following code (provided in the readme doesn't work )

```
 <button type="button" wire:click="$dispatch('showModal', ['alias' => 'pro.modals.restaurant.food-types-modal'])">
    {{ __('Not working button') }}
</button>
```
![Capture d’écran 2023-12-04 à 09 03 38](https://github.com/aliqasemzadeh/livewire-bootstrap-modal/assets/7534640/53b46a04-e2b1-438b-894e-8cbd0a3f7ee8)


But this code works 
```
 <button type="button" wire:click="$dispatch('showModal', { data: {alias:'pro.modals.restaurant.food-types-modal', params: {} } })">
    {{ __('Working button') }}
</button>
```

Have I missed something ?

- Laravel Framework 10.34.2
- Livewire  3.2.3
- AplineJs 3

**Comment by aliqasemzadeh** [comment]
I have this problem on aliqasemzadeh/bap and I am working on it.
Just wait.

**Comment by aliqasemzadeh** [comment]
@danyderigon 
Check update now.
