### ISSUE TITLE
Livewire v3

### ISSUE THREAD

**Issue by lifegiro** [aliqasemzadeh/livewire-bootstrap-modal#9]
Not compatible installing it via composer with Laravel Livewire v3. Are you planning to provide an update?

**Comment by aliqasemzadeh** [comment]
@lifegiro 
When v3 released I will make new version for this package.

**Comment by mozhulungdsuo** [comment]
Any update on when new version will be up?

**Comment by mozhuilungdsuo** [comment]
@lifegiro u can have a look at a fork of this package https://github.com/mozhuilungdsuo/livewire-bootstrap-modal

**Comment by aliqasemzadeh** [comment]
@mozhuilungdsuo 
Could please make a pull request to fix this issue?

**Comment by mozhuilungdsuo** [comment]
@aliqasemzadeh  can u have a look at my pull request?

**Comment by aliqasemzadeh** [comment]
@mozhuilungdsuo 
I did merge I will test your package on aliqasemzadeh/bap soon.

**Comment by ShakerAwad74** [comment]
@aliqasemzadeh 
When will be compatible installing it via composer with Laravel Livewire v3 ?

**Comment by aliqasemzadeh** [comment]
@ShakerAwad74 
Please check it now.

**Comment by aliqasemzadeh** [comment]
@mozhuilungdsuo 
It looks your version not work too.

**Comment by mozhuilungdsuo** [comment]
Can u let me know the issues? I'm using this in our projects and my team is using them fine. Provide the errors maybe? Thanks and great work on the original project

**Comment by aliqasemzadeh** [comment]
https://github.com/aliqasemzadeh/bap
In Admin/Index I want to open Admin/Create

@mozhuilungdsuo

**Comment by mozhuilungdsuo** [comment]
`
public function openCreate()
{
    $this->dispatch('showModal', ['alias' => 'admin.user.role.create', 'params' => ['name' => 'test']]);
}
`
@aliqasemzadeh  this is how i did it. I couldnt make it work from the template so im calling a wire:click="openCreate"

**Comment by kkbnet** [comment]
I can dispatch showModal in Livewire 3.0 when sending this (parameter is my product id):

<button class="btn" wire:click="$dispatch('showModal', { data: {alias:'ProductModal', params: {id: {{$product->id}} }}})">

**Comment by kkbnet** [comment]
I can run dispatch in LiveWire 3.0 when using this format (Product id is my parameter):

`<button class="btn" wire:click="$dispatch('showModal', { data: {alias:'ProductModal', params: {id: {{$product->id}} }}})">`

**Comment by aliqasemzadeh** [comment]
> I can run dispatch in LiveWire 3.0 when using this format (Product id is my parameter):
> 
> `<button class="btn" wire:click="$dispatch('showModal', { data: {alias:'ProductModal', params: {id: {{$product->id}} }}})">`

Just create function and then run it in livewire component.

**Comment by aliqasemzadeh** [comment]
Now livewire 3.x.x is stable.
